name: ClojureScript CI
on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        java: ['21']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: browser-actions/setup-chrome@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: latest
      - uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.m2/repository
          key: deps-${{ hashFiles('project.clj') }}
          restore-keys: deps-
      - run: npm install
      - run: lein doo chrome-headless none once
      - run: lein doo chrome-headless advanced once
